apiVersion: v1
kind: Config
clusters:
  - name: authn
    cluster:
      #server: https://192.168.169.137:9444/
      server: https://192.168.169.129:30965/
      insecure-skip-tls-verify: true
users:
  - name: kube-apiserver
contexts:
- context:
    cluster: authn
    user: kube-apiserver
  name: authn
current-context: authn
